In [1]:
#Bibliotecas
import pandas as pd
import numpy as np
import pickle
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils

In [2]:
#Carregamento da base de dados
base = pd.read_csv('idh_classificado.csv')
base.head()

PAÍS       PIB   ILE  IPC ClassIDH
0   África do Sul  0.004457  6.97   44    Médio
1         Albânia  0.000182  7.81   35    Médio
2        Alemanha  0.045774  7.91   80     Alto
3          Angola  0.001282  5.50   26    Médio
4  Arábia Saudita  0.008244  6.85   53     Alto

In [3]:
#Analisando o formato
base.shape

(156, 5)

In [4]:
#Definindo variáveis independentes e variáveis dependentes
previsores = base.iloc[:,2:4].values
classe = base.iloc[:,4].values
classe

array(['Médio', 'Médio', 'Alto', 'Médio', 'Alto', 'Médio', 'Alto',
       'Médio', 'Alto', 'Alto', 'Médio', 'Alto', 'Alto', 'Médio', 'Alto',
       'Alto', 'Médio', 'Alto', 'Médio', 'Médio', 'Médio', 'Médio',
       'Alto', 'Alto', 'Baixo', 'Baixo', 'Médio', 'Médio', 'Médio',
       'Médio', 'Alto', 'Alto', 'Alto', 'Baixo', 'Alto', 'Médio', 'Alto',
       'Médio', 'Médio', 'Baixo', 'Alto', 'Alto', 'Alto', 'Alto', 'Médio',
       'Médio', 'Médio', 'Alto', 'Médio', 'Alto', 'Alto', 'Alto', 'Alto',
       'Alto', 'Baixo', 'Médio', 'Alto', 'Alto', 'Médio', 'Baixo',
       'Médio', 'Alto', 'Alto', 'Médio', 'Médio', 'Baixo', 'Baixo',
       'Médio', 'Alto', 'Médio', 'Alto', 'Alto', 'Baixo', 'Alto', 'Médio',
       'Médio', 'Médio', 'Médio', 'Alto', 'Alto', 'Alto', 'Alto', 'Médio',
       'Alto', 'Médio', 'Alto', 'Médio', 'Médio', 'Alto', 'Médio',
       'Baixo', 'Médio', 'Alto', 'Alto', 'Médio', 'Médio', 'Alto',
       'Baixo', 'Baixo', 'Alto', 'Médio', 'Médio', 'Médio', 'Baixo',
       'Médi

In [5]:
#Codificando a coluna categórica (classe)
labelencoding = LabelEncoder()
base["ClassIDH"] = labelencoding.fit_transform(base["ClassIDH"])

In [6]:
#Criação da classe dummy
classe_dummy = np_utils.to_categorical(base["ClassIDH"])
classe_dummy

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0

In [7]:
#Dividindo dados entre treino e teste definindo 30% para teste
X_treino, X_teste, y_treino, y_teste = train_test_split(previsores,
                                                       classe_dummy,
                                                       test_size = 0.4,
                                                       random_state = 0)

In [8]:
#Criação da estrutura da rede neural com a classe Sequential (sequência de camadas)
modelo = Sequential()
#Primeira camada oculta e camada de entrada
modelo.add(Dense(units = 3, input_dim = 2))
#Segunda camada oculta
modelo.add(Dense(units = 3))
#Função de ativação Softmax para classificação de mais de duas classes (é gerada uma probablidade em cada neurônio)
modelo.add(Dense(units = 3, activation = 'softmax'))

In [9]:
#Sumário da estrutura
modelo.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 9         
                                                                 
 dense_1 (Dense)             (None, 3)                 12        
                                                                 
 dense_2 (Dense)             (None, 3)                 12        
                                                                 
Total params: 33
Trainable params: 33
Non-trainable params: 0
_________________________________________________________________


In [10]:
#Configuração de parâmetros da rede neural (adam = algoritmo de ajuste de pesos, loss = cálculo do erro)
modelo.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
#Treinamento, dividindo a base de treino com uma porção para validação (validation_data)
modelo.fit(X_treino, y_treino, epochs = 500, 
           validation_data = (X_teste, y_teste))

Epoch 1/500
3/3 [==============================] - 0s 60ms/step - loss: 41.8479 - accuracy: 0.0968 - val_loss: 49.5302 - val_accuracy: 0.1270
Epoch 2/500
3/3 [==============================] - 0s 9ms/step - loss: 40.0672 - accuracy: 0.0968 - val_loss: 47.9690 - val_accuracy: 0.1270
Epoch 3/500
3/3 [==============================] - 0s 10ms/step - loss: 38.3012 - accuracy: 0.0968 - val_loss: 46.4752 - val_accuracy: 0.1270
Epoch 4/500
3/3 [==============================] - 0s 9ms/step - loss: 36.6888 - accuracy: 0.0968 - val_loss: 45.2496 - val_accuracy: 0.1270
Epoch 5/500
3/3 [==============================] - 0s 9ms/step - loss: 35.5187 - accuracy: 0.1720 - val_loss: 44.7340 - val_accuracy: 0.3175
Epoch 6/500
3/3 [==============================] - 0s 9ms/step - loss: 35.0793 - accuracy: 0.4516 - val_loss: 44.5378 - val_accuracy: 0.3175
Epoch 7/500
3/3 [==============================] - 0s 9ms/step - loss: 34.8739 - accuracy: 0.4516 - val_loss: 44.2655 - val_accuracy: 0.3175
Epoch 8/500

In [11]:
previsoes = modelo.predict(X_teste)
previsoes = (previsoes > 0.5)
previsoes

2/2 [==============================] - 0s 2ms/step


array([[ True, False, False],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [Fa

In [12]:
'''Precisamos criar uma Matriz de Confudão para comparar a taxa 
de acerto das previsoes, para isso é necessário passar os dados 
reais de teste(y_teste) para uma variável(y_teste_matriz) e os 
dados das previsões para a variável(y_previsão_matriz)'''
y_teste_matriz = [np.argmax(t) for t in y_teste]
y_previsao_matriz = [np.argmax(t) for t in previsoes]

In [13]:
#Criando a Matriz de Confusão para verificar a taxa de acerto
confusao = confusion_matrix(y_teste_matriz, y_previsao_matriz)
confusao

array([[17,  0,  3],
       [ 0,  0,  8],
       [ 5,  0, 30]], dtype=int64)

In [14]:
#Verificando a performance de acerto das previsoes dos dados de teste
taxa_acerto = accuracy_score(y_teste_matriz, y_previsao_matriz)
taxa_acerto

0.746031746031746

In [15]:
#Prevendo um novo registro
ile = 5.60
ipc = 40
novo = np.array([[ile, ipc]])
previsao = modelo.predict(novo)
if previsao[:, 0] >= 0.50:
     print('O IDH tende a ser ALTO!')
elif previsao[:, 1] >= 0.50:
     print('O IDH tende a ser BAIXO!')
else:
     print('O IDH tende a ser MÉDIO!')

1/1 [==============================] - 0s 12ms/step
O IDH tende a ser MÉDIO!


In [17]:
#pickle.dump(modelo, open('modelo.pkl', 'wb'))

In [ ]:
# path = 'modelo.h5'
# modelo.save(path)