In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

In [2]:
base = pd.read_csv('../data/economicdata2020v2.csv')
pd.set_option('display.max_columns', None)
base

countries  judicial independence  impartial courts  \
0        Albania                   4.19              4.07   
1        Algeria                   4.09              4.04   
2         Angola                   4.06              3.39   
3      Argentina                   4.73              4.03   
4        Armenia                   4.69              5.54   
..           ...                    ...               ...   
158    Venezuela                   2.20              1.18   
159      Vietnam                   3.48              4.30   
160  Yemen, Rep.                   2.94              2.25   
161       Zambia                   4.89              4.52   
162     Zimbabwe                   4.11              3.29   

     protection of property rights  \
0                             3.84   
1                             5.13   
2                             3.74   
3                             4.58   
4                             6.37   
..                             ...   
158                           0.98   
159                           4.97   
160                           2.78   
161                           4.78   
162                           3.06   

     military interference in rule of law and politics  \
0                                                 8.33   
1                                                 3.33   
2                                                 4.17   
3                                                 7.50   
4                                                 5.83   
..                                                 ...   
158                                               1.67   
159                                               5.00   
160                                               4.17   
161                                               8.33   
162                                               3.33   

     integrity of the legal system  legal enforcement of contracts  \
0                             5.40                            3.91   
1                             4.79                            4.39   
2                             4.50                            2.30   
3                             4.84                            3.82   
4                             5.77                            5.20   
..                             ...                             ...   
158                           2.22                            2.44   
159                           5.43                            5.09   
160                           2.77                            3.78   
161                           5.12                            3.51   
162                           4.60                            2.37   

     regulatory restrictions on the sale of real property  \
0                                                 6.72      
1                                                 6.63      
2                                                 5.52      
3                                                 6.86      
4                                                 9.82      
..                                                 ...      
158                                               8.14      
159                                               8.79      
160                                               9.05      
161                                               6.03      
162                                               7.05      

     reliability of police  gender legal rights adjustment  \
0                     5.61                            1.00   
1                     6.35                            0.71   
2                     3.81                            0.88   
3                     4.41                            0.88   
4                     6.67                            1.00   
..                     ...                             ...   
158                   1.37                            1.00   
159                   5.30                        

In [3]:
df = base.drop(['countries', 'human development index'], axis=1)
df.head()

judicial independence  impartial courts  protection of property rights  \
0                   4.19              4.07                           3.84   
1                   4.09              4.04                           5.13   
2                   4.06              3.39                           3.74   
3                   4.73              4.03                           4.58   
4                   4.69              5.54                           6.37   

   military interference in rule of law and politics  \
0                                               8.33   
1                                               3.33   
2                                               4.17   
3                                               7.50   
4                                               5.83   

   integrity of the legal system  legal enforcement of contracts  \
0                           5.40                            3.91   
1                           4.79                            4.39   
2                           4.50                            2.30   
3                           4.84                            3.82   
4                           5.77                            5.20   

   regulatory restrictions on the sale of real property  \
0                                               6.72      
1                                               6.63      
2                                               5.52      
3                                               6.86      
4                                               9.82      

   reliability of police  gender legal rights adjustment  \
0                   5.61                            1.00   
1                   6.35                            0.71   
2                   3.81                            0.88   
3                   4.41                            0.88   
4                   6.67                            1.00   

   legal system & property rights  \
0                            5.26   
1                            4.13   
2                            3.71   
3                            4.80   
4                            6.24   

   revenue from trade taxes (% of trade sector)  mean tariff rate  \
0                                          9.57              9.28   
1                                          8.48              6.22   
2                                          9.39              7.96   
3                                          4.93              7.32   
4                                          8.94              8.76   

   standard deviation of tariff rates  tariffs  non-tariff trade barriers  \
0                                8.08     8.98                       6.81   
1                                5.92     6.87                       4.56   
2                                4.00     7.12                       4.70   
3                                5.87     6.04                       5.07   
4                                7.59     8.43                       5.69   

   compliance costs of importing and exporting  regulatory trade barriers  \
0                                         9.41                       8.11   
1                                         0.48                       2.52   
2                                         2.51                       3.60   
3                                         5.65                       5.36   
4                                         9.32                       7.50   

   black market exchange rates  financial openness  capital controls  \
0                        10.00                4.17              4.62   
1                         4.36                1.64              0.77   
2                        10.00                0.00              2.31   
3                         0.00                2.84              0.00   
4                        10.00                8.36              6.15   

   freedom of foreigners to visit  \
0                            8.63   
1      

In [4]:
X = df.iloc[:,0:43].values
y = df.iloc[:,43].values
print(X,'\n')
print(y)

[[ 4.19  4.07  3.84 ...  6.7   7.11 36.  ]
 [ 4.09  4.04  5.13 ...  5.69  5.78 36.  ]
 [ 4.06  3.39  3.74 ...  5.7   6.23 27.  ]
 ...
 [ 2.94  2.25  2.78 ...  4.12  3.58 15.  ]
 [ 4.89  4.52  4.78 ...  6.25  6.3  33.  ]
 [ 4.11  3.29  3.06 ...  5.34  6.08 24.  ]] 

['high' 'high' 'medium' 'very_high' 'high' 'very_high' 'very_high' 'high'
 'very_high' 'very_high' 'medium' 'high' 'very_high' 'very_high' 'medium'
 'low' 'medium' 'medium' 'high' 'medium' 'high' 'very_high' 'high' 'low'
 'low' 'medium' 'medium' 'medium' 'very_high' 'low' 'low' 'very_high'
 'high' 'high' 'medium' 'low' 'medium' 'very_high' 'low' 'very_high'
 'very_high' 'very_high' 'very_high' 'low' 'high' 'high' 'high' 'medium'
 'very_high' 'medium' 'low' 'high' 'very_high' 'very_high' 'high' 'low'
 'very_high' 'very_high' 'medium' 'very_high' 'medium' 'low' 'low' 'high'
 'low' 'medium' 'very_high' 'very_high' 'very_high' 'medium' 'high' 'high'
 'medium' 'very_high' 'very_high' 'very_high' 'high' 'very_high' 'high'
 'very_h

In [5]:
model = LogisticRegression(max_iter=2000, n_jobs=-1)

In [6]:
selector = RFE(model)
selector = selector.fit(X, y)

In [7]:
selector.ranking_

array([ 1,  1,  1,  1,  9,  2,  4, 11,  1,  1,  1,  1,  1, 10,  1,  8,  1,
        1, 12,  6, 14,  5, 21, 22, 16,  1, 13,  7,  1, 23, 17, 19, 18,  3,
        1,  1,  1,  1,  1,  1,  1, 15, 20])

In [8]:
features = selector.get_support(indices=True)
features

array([ 0,  1,  2,  3,  8,  9, 10, 11, 12, 14, 16, 17, 25, 28, 34, 35, 36,
       37, 38, 39, 40], dtype=int64)

In [9]:
features = np.append(features, 44)
features = np.append(features, 45)

In [10]:
features

array([ 0,  1,  2,  3,  8,  9, 10, 11, 12, 14, 16, 17, 25, 28, 34, 35, 36,
       37, 38, 39, 40, 44, 45], dtype=int64)

In [11]:
base = base.iloc[:,features]

In [12]:
base

countries  judicial independence  impartial courts  \
0        Albania                   4.19              4.07   
1        Algeria                   4.09              4.04   
2         Angola                   4.06              3.39   
3      Argentina                   4.73              4.03   
4        Armenia                   4.69              5.54   
..           ...                    ...               ...   
158    Venezuela                   2.20              1.18   
159      Vietnam                   3.48              4.30   
160  Yemen, Rep.                   2.94              2.25   
161       Zambia                   4.89              4.52   
162     Zimbabwe                   4.11              3.29   

     protection of property rights  reliability of police  \
0                             3.84                   5.61   
1                             5.13                   6.35   
2                             3.74                   3.81   
3                             4.58                   4.41   
4                             6.37                   6.67   
..                             ...                    ...   
158                           0.98                   1.37   
159                           4.97                   5.30   
160                           2.78                   3.43   
161                           4.78                   3.58   
162                           3.06                   3.90   

     gender legal rights adjustment  legal system & property rights  \
0                              1.00                            5.26   
1                              0.71                            4.13   
2                              0.88                            3.71   
3                              0.88                            4.80   
4                              1.00                            6.24   
..                              ...                             ...   
158                            1.00                            2.52   
159                            0.94                            5.14   
160                            0.41                            2.75   
161                            0.94                            4.95   
162                            1.00                            3.97   

     revenue from trade taxes (% of trade sector)  mean tariff rate  tariffs  \
0                                            9.57              9.28     8.98   
1                                            8.48              6.22     6.87   
2                                            9.39              7.96     7.12   
3                                            4.93              7.32     6.04   
4                                            8.94              8.76     8.43   
..                                            ...               ...      ...   
158                                          8.45              7.24     7.26   
159                                          9.12              8.10     7.54   
160                                          8.92              8.48     8.40   
161                                          8.82              7.30     7.18   
162                                          7.61              8.20     7.61   

     compliance costs of importing and exporting  regulatory trade barriers  \
0                                           9.41                       8.11   
1                                           0.48                       2.52   
2                                           2.51                       3.60   
3                                           5.65                       5.36   
4                                           9.32                       7.50   
..                                           ...                        ...   
158                                        10.00                       6.88   
159                                         5.75                       5.32   
160             

In [13]:
#base.to_csv('../data/economicdata2020v3.csv', index=False)