In [307]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.metrics import confusion_matrix, accuracy_score

In [308]:
base = pd.read_csv('../data/economicdata2020v3.csv', sep=',')
base.head()

countries  judicial independence  impartial courts  \
0    Albania                   4.19              4.07   
1    Algeria                   4.09              4.04   
2     Angola                   4.06              3.39   
3  Argentina                   4.73              4.03   
4    Armenia                   4.69              5.54   

   protection of property rights  \
0                           3.84   
1                           5.13   
2                           3.74   
3                           4.58   
4                           6.37   

   military interference in rule of law and politics  \
0                                               8.33   
1                                               3.33   
2                                               4.17   
3                                               7.50   
4                                               5.83   

   integrity of the legal system  legal enforcement of contracts  \
0                           5.40                            3.91   
1                           4.79                            4.39   
2                           4.50                            2.30   
3                           4.84                            3.82   
4                           5.77                            5.20   

   reliability of police  legal system & property rights  \
0                   5.61                            5.26   
1                   6.35                            4.13   
2                   3.81                            3.71   
3                   4.41                            4.80   
4                   6.67                            6.24   

   non-tariff trade barriers  ...  regulatory trade barriers  \
0                       6.81  ...                       8.11   
1                       4.56  ...                       2.52   
2                       4.70  ...                       3.60   
3                       5.07  ...                       5.36   
4                       5.69  ...                       7.50   

   financial openness  controls of the movement of capital and people  \
0                4.17                                            5.80   
1                1.64                                            0.80   
2                0.00                                            0.77   
3                2.84                                            0.95   
4                8.36                                            4.84   

   freedom to trade internationally  regulatory burden  \
0                              8.22               6.00   
1                              3.64               2.22   
2                              5.37               3.11   
3                              3.09               5.56   
4                              7.69               5.11   

   impartial public administration  business regulations  \
0                             6.00                  6.70   
1                             2.58                  5.69   
2                             4.70                  5.70   
3                             7.27                  6.23   
4                             6.26                  7.12   

   corruption perceptions index  human development index  categories  
0                          36.0                    0.796        high  
1                          36.0                    0.745        high  
2                          27.0                    0.586      medium  
3                          42.0                    0.842   very_high  
4                          49.0                    0.759        high  

[5 rows x 21 columns]

In [309]:
base = base.drop(['human development index'], axis=1)

In [310]:
class_orderly = pd.CategoricalDtype(categories = ['very_high', 'high', 'medium', 'low'], ordered=True)
base['categories'] = base['categories'].astype(class_orderly)

In [311]:
base.sort_values('categories', ascending=True, inplace=True)
base

countries  judicial independence  impartial courts  \
81   Korea, Rep.                   6.06              6.74   
37    Costa Rica                   7.32              6.15   
79    Kazakhstan                   4.25              4.17   
39       Croatia                   5.56              4.83   
40        Cyprus                   6.83              6.23   
..           ...                    ...               ...   
24       Burundi                   3.74              3.34   
23  Burkina Faso                   5.02              3.80   
61        Guinea                   4.34              3.56   
95          Mali                   5.25              3.58   
43      Djibouti                   6.10              3.99   

    protection of property rights  \
81                           6.69   
37                           6.61   
79                           5.64   
39                           4.59   
40                           6.62   
..                            ...   
24                           4.31   
23                           4.62   
61                           3.99   
95                           4.00   
43                           4.33   

    military interference in rule of law and politics  \
81                                               6.67   
37                                              10.00   
79                                               8.33   
39                                               8.33   
40                                               8.33   
..                                                ...   
24                                               6.40   
23                                               3.33   
61                                               0.83   
95                                               3.33   
43                                               6.40   

    integrity of the legal system  legal enforcement of contracts  \
81                           8.04                            6.88   
37                           6.59                            3.52   
79                           5.19                            5.04   
39                           7.16                            4.64   
40                           8.13                            4.00   
..                            ...                             ...   
24                           3.28                            2.81   
23                           6.25                            2.14   
61                           3.96                            5.39   
95                           5.60                            2.63   
43                           4.31                            3.16   

    reliability of police  legal system & property rights  \
81                   7.24                            6.65   
37                   6.03                            6.66   
79                   5.24                            5.62   
39                   5.44                            6.12   
40                   6.40                            6.33   
..                    ...                             ...   
24                   5.37                            4.09   
23                   5.72                            4.07   
61                   5.30                            3.99   
95                   3.96                            3.52   
43                   5.60                            4.06   

    non-tariff trade barriers  compliance costs of importing and exporting  \
81                       5.63                                         9.58   
37                       4.97                                         7.47   
79                       5.80                                         4.89   
39                       6.72                                         9.98   
40                       6.79                                         9.32   
..                        ...                                          ...   
24                       4.55       

In [312]:
base.groupby(['categories']).size()

categories
very_high    63
high         35
medium       35
low          30
dtype: int64

In [313]:
x = base.iloc[:, 1:19].values
y = base.iloc[:, 19]

In [314]:
print(x)
print(y)

[[ 6.06  6.74  6.69 ...  7.88  8.06 61.  ]
 [ 7.32  6.15  6.61 ...  9.21  7.13 57.  ]
 [ 4.25  4.17  5.64 ...  4.46  7.07 38.  ]
 ...
 [ 4.34  3.56  3.99 ...  2.51  5.56 28.  ]
 [ 5.25  3.58  4.   ...  4.29  6.08 30.  ]
 [ 6.1   3.99  4.33 ...  5.07  6.69 27.  ]]
81    very_high
37    very_high
79    very_high
39    very_high
40    very_high
        ...    
24          low
23          low
61          low
95          low
43          low
Name: categories, Length: 163, dtype: category
Categories (4, object): ['very_high' < 'high' < 'medium' < 'low']


In [315]:
y.replace({'very_high':3, 'high':2, 'medium':1, 'low':0}, inplace=True)

In [316]:
groups, quantities = np.unique(y, return_counts=True)

In [317]:
groups

array([0, 1, 2, 3], dtype=int64)

In [318]:
quantities

array([30, 35, 35, 63], dtype=int64)

In [319]:
#Definindo o número de clusters(grupos)
cluster = KMeans(n_clusters=4)
cluster.fit(x)

KMeans(n_clusters=4)

In [320]:
#Visualizando os centros utilizados pelo agrupador
centroids = cluster.cluster_centers_ 
centroids

array([[ 7.83913043,  7.88956522,  8.08608696,  9.27478261,  8.49695652,
         6.30347826,  8.09695652,  7.97173913,  6.73695652,  9.32913043,
         8.0326087 ,  9.70173913,  5.96347826,  8.02478261,  7.14869565,
         8.97130435,  8.10304348, 78.65217391],
       [ 4.28088889,  3.24      ,  4.06266667,  4.41      ,  4.15466667,
         3.22355556,  4.33311111,  3.73911111,  4.93777778,  3.95533333,
         4.44288889,  3.426     ,  2.28488889,  5.58822222,  2.736     ,
         3.564     ,  5.46733333, 24.28888889],
       [ 5.14666667,  4.5835    ,  5.13183333,  5.895     ,  5.49283333,
         4.153     ,  5.04916667,  5.02433333,  5.47433333,  6.34666667,
         5.911     ,  4.13766667,  2.63433333,  6.36933333,  5.11066667,
         5.22966667,  6.551     , 38.27266667],
       [ 6.34457143,  6.09428571,  6.37771429,  7.96971429,  7.164     ,
         4.85571429,  6.53628571,  6.34571429,  6.17028571,  8.35542857,
         7.262     ,  7.96371429,  4.79571429,  7.426

In [321]:
#Visualizando o agrupamento realizado
grouping = cluster.labels_
grouping

array([3, 3, 2, 3, 3, 3, 0, 2, 3, 0, 0, 0, 0, 0, 0, 2, 3, 0, 3, 3, 0, 2,
       3, 0, 3, 2, 3, 0, 3, 3, 3, 3, 0, 3, 3, 1, 2, 2, 2, 0, 2, 0, 0, 2,
       0, 0, 0, 3, 2, 0, 3, 0, 2, 3, 3, 3, 2, 0, 0, 3, 3, 0, 3, 2, 2, 1,
       2, 2, 2, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 2, 1, 3, 2, 2, 2, 1, 2, 2,
       2, 2, 2, 1, 2, 3, 2, 2, 2, 3, 3, 1, 1, 1, 2, 1, 1, 1, 1, 1, 3, 1,
       3, 1, 1, 2, 2, 1, 3, 2, 2, 1, 2, 1, 1, 1, 2, 2, 1, 2, 1, 2, 1, 2,
       2, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 3, 1, 2,
       1, 1, 2, 2, 1, 2, 1, 1, 1])

In [322]:
#Contagem de grupos e quantidades de cada grupo
groups2, quantities2 = np.unique(grouping, return_counts=True)

In [323]:
#Quantidade de grupos
groups2

array([0, 1, 2, 3])

In [324]:
#Quantidades dentro de cada grupo
print(quantities)
print(quantities2)

[30 35 35 63]
[23 45 60 35]


In [325]:
#Analisando a matriz de confusão 
results = confusion_matrix(y, grouping)
results

array([[ 0, 19, 10,  1],
       [ 0, 19, 12,  4],
       [ 0,  6, 25,  4],
       [23,  1, 13, 26]], dtype=int64)

In [326]:
#Verificando a performance de acerto do agrupamento K-means
rate = accuracy_score(y, grouping)
rate

0.4294478527607362