In [1]:
#Bibliotecas
import pandas as pd
import numpy as np

In [2]:
#Carregamento da base de dados
base = pd.read_csv('idh_pontuado.csv')
base.head()

País       PIB   ILE  IPC    IDH
0   África do Sul  0.004457  6.97   44  0.709
1         Albânia  0.000182  7.81   35  0.795
2        Alemanha  0.045774  7.91   80  0.947
3          Angola  0.001282  5.50   26  0.581
4  Arábia Saudita  0.008244  6.85   53  0.854

In [3]:
#Analisando formato
base.shape

(156, 5)

In [4]:
#Analisando tipos
base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   País    156 non-null    object 
 1   PIB     156 non-null    float64
 2   ILE     156 non-null    float64
 3   IPC     156 non-null    int64  
 4   IDH     156 non-null    float64
dtypes: float64(3), int64(1), object(1)
memory usage: 6.2+ KB


In [5]:
#Definindo variáveis independentes e variáveis dependentes
X = base.iloc[:,1:4].values
y = base.iloc[:,4].values
X

array([[4.4570e-03, 6.9700e+00, 4.4000e+01],
       [1.8200e-04, 7.8100e+00, 3.5000e+01],
       [4.5774e-02, 7.9100e+00, 8.0000e+01],
       [1.2820e-03, 5.5000e+00, 2.6000e+01],
       [8.2440e-03, 6.8500e+00, 5.3000e+01],
       [2.1030e-03, 4.9000e+00, 3.5000e+01],
       [6.2890e-03, 5.5000e+00, 4.5000e+01],
       [1.5000e-04, 8.0300e+00, 4.2000e+01],
       [1.6160e-02, 8.2000e+00, 7.7000e+01],
       [5.5230e-03, 7.8600e+00, 7.7000e+01],
       [5.6000e-05, 6.4400e+00, 3.0000e+01],
       [1.5000e-04, 7.5600e+00, 6.4000e+01],
       [4.5700e-04, 7.3300e+00, 4.2000e+01],
       [3.4920e-03, 6.0500e+00, 2.6000e+01],
       [6.1000e-05, 6.9100e+00, 6.2000e+01],
       [6.4440e-03, 7.6200e+00, 7.5000e+01],
       [1.7200e-04, 6.6200e+00, 4.1000e+01],
       [7.2200e-04, 6.8800e+00, 4.5000e+01],
       [4.9100e-04, 6.2800e+00, 3.1000e+01],
       [2.4400e-04, 6.8600e+00, 3.6000e+01],
       [2.2500e-04, 7.6200e+00, 6.1000e+01],
       [1.6512e-02, 6.6300e+00, 3.5000e+01],
       [1.

In [6]:
#Verificando a correlação entre PIB e IDH
corrPIB = np.corrcoef(X[:,0], y)
corrPIB

array([[1.        , 0.20176387],
       [0.20176387, 1.        ]])

In [7]:
#Analisando a correlação entre ILE e IDH
corrILE = np.corrcoef(X[:,1], y)
corrILE

array([[1.       , 0.6800175],
       [0.6800175, 1.       ]])

In [8]:
#Analisando a correlação entre IPC e IDH
corrIPC = np.corrcoef(X[:,2], y)
corrIPC

array([[1.        , 0.76337469],
       [0.76337469, 1.        ]])

In [9]:
#Ordenando por maior IDH
base.sort_values(['IDH'], ascending = False)

País       PIB   ILE  IPC    IDH
113                    Noruega  0.005256  7.72   84  0.957
78                     Irlanda  0.004634  8.21   74  0.955
141                      Suíça  0.008570  8.48   85  0.955
70                   Hong Kong  0.004391  8.91   76  0.949
79                    Islândia  0.000314  7.90   78  0.949
..                         ...       ...   ...  ...    ...
98                        Mali  0.000020  5.83   29  0.434
25                     Burundi  0.000041  5.65   19  0.433
33                       Chade  0.000133  5.60   20  0.398
126  República Centro-Africana  0.000002  5.36   25  0.397
111                      Níger  0.000112  5.97   32  0.394

[156 rows x 5 columns]